grantly/src/App.js
grantly/src/actions/index.js
grantly/src/actions/types.js
grantly/src/views/Home.js

Michael harris

---

grantly/package-lock.json
grantly/package.json
grantly/src/App.js
grantly/src/App.scss
grantly/src/components/grants/Grant.js
grantly/src/index.css
grantly/src/views/Home.js

Add in three column grid layout with Material UI and Button

Rory murray

---

grantly/src/App.js
grantly/src/App.scss
grantly/src/components/Navbar.js
grantly/src/components/grants/Grant.js
grantly/src/components/grants/GrantShowcase.js
grantly/src/views/Home.js

Grid properly split

---

grantly/.gitignore

Auth config

---

grantly/src/App.js
grantly/src/auth_config.json
grantly/src/components/Filters.js
grantly/src/components/MobileFilters.js
grantly/src/components/MobileTabs.js
grantly/src/components/Navbar.js
grantly/src/components/SubmitForm.js
grantly/src/components/grants/GrantList.js
grantly/src/components/grants/GrantShowcase.js
grantly/src/index.js
grantly/src/styles/Theme.js
grantly/src/styles/filterStyles.js
grantly/src/styles/homeStyles.js
grantly/src/styles/landingStyles.js
grantly/src/styles/mobileFilterStyles.js
grantly/src/util/ExternalApi.js
grantly/src/views/Home.js
grantly/src/views/Landing.js

Add results info of how many grants are showing

---

grantly/src/App.js
grantly/src/components/Filters.js
grantly/src/components/Navbar.js
grantly/src/components/Sitemap.js
grantly/src/components/SubmitForm.js
grantly/src/components/grants/Grant.js
grantly/src/components/grants/GrantList.js
grantly/src/components/grants/GrantShowcase.js
grantly/src/components/mobile/MobileFilters.js
grantly/src/components/mobile/MobileTabs.js
grantly/src/reducers/index.js
grantly/src/styles/FormStyles.js
grantly/src/styles/GrantStyles.js
grantly/src/styles/filterStyles.js
grantly/src/styles/grantShowcaseStyles.js
grantly/src/styles/homeStyles.js
grantly/src/styles/landingStyles.js
grantly/src/styles/navStyles.js
grantly/src/styles/sitemapStyles.js
grantly/src/views/Admin.js
grantly/src/views/Home.js

Added sitemap as requested by Zack matching UX design
Added mobile nav back in displaying links that are available on the site map
Grant showcase no longer show if no grants have been fetched yet
Changed nav "Home" link to "Grants"
Removed login button on nav
Apply to Grant Button now links to grant website
Mobile responsiveness is still being worked on. Issues with form component on mobile

Sitemap added

---

grantly/src/components/Filters.js
grantly/src/views/Landing.js

This is basically just an added console.log to debug the styling issues on deployed sites!

check the location when delployed

---

grantly/src/App.js
grantly/src/App.scss
grantly/src/components/Navbar.js
grantly/src/components/grants/Grant.js
grantly/src/components/grants/styles/DialogStyles.js
grantly/src/components/grants/styles/GrantStyles.js
grantly/src/styles/aboutStyles.js
grantly/src/styles/adminStyles.js
grantly/src/styles/homeStyles.js
grantly/src/styles/landingStyles.js
grantly/src/styles/mobileTabStyles.js
grantly/src/styles/navStyles.js
grantly/src/styles/sitemapStyles.js
grantly/src/views/Admin.js
grantly/src/views/Home.js

Misc style changes as per trello checklist.
-Added nav option to admin while in tablet view
-Changed styling on tablet view for about and grant components
- [x ] There are no merge conflicts

Reed james

---

grantly/package-lock.json
grantly/package.json
grantly/src/index.js

Configured sentry.io

---

grantly/src/components/Navbar.js

Changed Signup to Login for a better UI

Nav Bar Login rewording

---

grantly/src/App.js
grantly/src/actions/index.js
grantly/src/components/AdminForm.js
grantly/src/components/Navbar.js
grantly/src/components/grants/GrantList.js
grantly/src/components/grants/GrantTable.js
grantly/src/components/onRowUpdateFN.js
grantly/src/components/submitForm/GrantFocus.js
grantly/src/reducers/index.js

Feature admin table

---

grantly/src/components/Navbar.js

added a table link to nav drawer

---

grantly/src/components/AdminForm.js

updated Admin form to remove 'suggestions' property

---

grantly/src/components/grants/GrantTable.js

fixed edit grant on GrantTable

---

grantly/src/actions/index.js
grantly/src/components/grants/GrantTable.js

Working on deleting suggestions
Co-authored-by: Kristin <kristinbarr@gmail.com>
Co-authored-by: Daniel <daniel.jones2000@gmail.com>
Co-authored-by: Benita <nicole.beamer@icloud.com>
Co-authored-by: Ben <bigriffin94@gmail.com>
Co-authored-by: Mario <mario.amaya.web@gmail.com>

Suggestion Drop Down

---

grantly/src/styles/navStyles.js

Cleaning up the nav bar color w Benita

---

grantly/src/components/Navbar.js
grantly/src/components/grants/GrantTable.js
grantly/src/styles/navStyles.js

It is being overridden by MUI
Co-authored-by: Kristin <kristinbarr@gmail.com>
Co-authored-by: Daniel <daniel.jones2000@gmail.com>
Co-authored-by: Benita <nicole.beamer@icloud.com>
Co-authored-by: Ben <bigriffin94@gmail.com>

Debugging Nav Bar color

---

grantly/src/components/grants/GrantTable.js
grantly/src/styles/navStyles.js

Netlify is moving our burger button to flex-end
Co-authored-by: Kristin <kristinbarr@gmail.com>
Co-authored-by: Daniel <daniel.jones2000@gmail.com>
Co-authored-by: Benita <nicole.beamer@icloud.com>
Co-authored-by: Ben <bigriffin94@gmail.com>

Hamburger Button on Netlify

---

grantly/src/components/Navbar.js
grantly/src/components/grants/GrantTable.js
grantly/src/styles/navStyles.js

Suggestions fix

---

grantly/src/components/grants/GrantTable.js

netlify fix

---

grantly/src/components/Navbar.js

media query hamburger for nav

---

grantly/src/components/Navbar.js

nav menu options conditionally rendering

---

grantly/src/components/Navbar.js
grantly/src/components/grants/TableSuggestions.js

Config auth0

---

grantly/src/App.js
grantly/src/components/SubmitForm.js
grantly/src/components/filter/NewFilters.tsx
grantly/src/components/grants/Grant.js
grantly/src/components/grants/GrantList.js
grantly/src/components/grants/GrantShowcase.js
grantly/src/store/grants/grantReducer.ts
grantly/src/store/grants/grantTypes.ts
grantly/src/store/grants/useGrantActions.tsx
grantly/src/views/Home.js

Adding Actions to get WEBPAGE Functionable.

Store-Refactor

---

grantly/src/components/suggestion/Suggestion.jsx
grantly/src/components/suggestion/formElements/GrandDemoForm.jsx
grantly/src/components/suggestion/formElements/GrantFoucusForm.jsx
grantly/src/components/suggestion/formElements/GrantInfoForm.jsx
grantly/src/components/suggestion/formUtils/formValues.js
grantly/src/index.jsx
package-lock.json

set up material structure - New Features - Incomplete

---

grantly/src/components/about/About.jsx
grantly/src/components/auth0/Auth0Wrapper.jsx
grantly/src/components/auth0/useGetToken.jsx
grantly/src/components/navbar/Navbar.jsx
grantly/src/components/routing/Routes.jsx
grantly/src/index.jsx
grantly/src/store/user/useUserActions.tsx
grantly/src/store/user/userReducer.ts
grantly/src/store/user/userTypes.ts

Added useGetToken Hook, adding Token to Redux Storage

Introducing the Token to FE

---

grantly/src/components/routing/Routes.jsx

Fixed Routes

---

grantly/src/components/userProfile/UserSettingsForm.js
grantly/src/components/userProfile/userData.js
grantly/src/components/userProfile/userSettings.js

Completed front end visuals for editing states for user settings

completed editing logicfor user settings

---

grantly/src/components/navbar/Navbar.jsx
grantly/src/components/routing/Routes.jsx
grantly/src/components/userProfile/UserSettingsForm.js
grantly/src/components/userProfile/userData.js
grantly/src/components/userProfile/userSettings.js
grantly/src/hooks/useForm.jsx
grantly/src/store/user/useUserActions.tsx
grantly/src/store/user/userReducer.ts
grantly/src/store/user/userTypes.ts

Finishing up 1.5 Release Canvas

Last minute changes to User Settings Form

---

grantly/public/index.html
grantly/src/components/grants/GrantShowcase.spec.js

Added some testing to start. Also added meta tag for google verification

Staging jackson

---

src/components/suggestion/formElements/TextFormField.jsx
src/components/userProfile/UserSettingsForm.js
src/components/userProfile/userData.js
src/components/userProfile/userSettings.js

Completed Edit functionality for user dashboard

completed edit functionality

---

package.json

Removing ENV File from Repository

Changed GitIgnore and removed ENV File

---

.gitignore
src/components/navbar/Navbar.jsx
src/components/routing/AdminRoute.jsx
src/components/routing/PrivateRoute.jsx
src/components/routing/Routes.jsx
src/components/userProfile/userData.js
src/components/userProfile/userSettings.js
src/store/user/useUserActions.tsx
src/store/user/userReducer.ts
src/store/user/userTypes.ts

User Data being saved on Auth0

User Data being saved on Auth0

---

src/components/grants/GrantContainer.jsx
src/components/grants/list/GrantList.jsx
src/components/grants/list/GrantList.spec.js
src/components/grants/list/testGrantValues.js

added more tests

---

.env
src/components/admin/AdminUserTable/UserTable.js
src/components/admin/GrantTable.jsx
src/components/filter/Filters.jsx
src/components/filter/NewFilters.tsx
src/components/filter/formState.ts
src/components/grants/GrantContainer.jsx
src/components/navbar/Navbar.jsx
src/components/routing/AdminRoute.jsx
src/components/suggestion/formElements/TextFormField.jsx
src/components/userProfile/UserSettingsForm.js
src/components/userProfile/userData.js
src/components/userProfile/userSettings.js
src/store/admin/adminReducer.ts
src/store/admin/adminTypes.ts
src/store/admin/useAdminActions.tsx
src/store/filters/Filters.ts
src/store/filters/filterReducer.ts
src/store/filters/useFilterActions.tsx
src/store/grants/grantReducer.ts
src/store/grants/grantTypes.ts
src/store/rooterReducer.ts
src/store/useActions.tsx
src/store/user/useUserActions.tsx
src/store/user/userReducer.ts
src/store/user/userTypes.ts

Integrated the User Dashboard with Auth 0

User Dashboard Integrated with Auth 0

---

package.json
src/components/grants/GrantContainer.jsx
src/components/navbar/navbar.spec.js

fixed bug and added a couple more fe tests

---

.github/workflows/ci.yml
package.json
src/components/navbar/Navbar.jsx
src/store/admin/adminReducer.ts
src/store/admin/adminTypes.ts
src/store/admin/useAdminActions.tsx
src/store/user/userReducer.ts
src/store/user/userTypes.ts

Code Climate Coverage Testing
Doesn't fix anything.....

Code Climate Testing

---

src/components/admin/AdminUserTable/UserTable.js
src/components/admin/GrantTable.jsx
src/components/navbar/SideMenu.jsx
src/components/navbar/navbar.spec.js

Testing fe jackson

---

src/components/filter/NewFilters.tsx
src/components/navbar/Navbar.jsx

Fixed Moderator Action
Fixes Moderators not being found

Fixed Moderator Action

---

src/store/admin/useAdminActions.tsx

Changed routes from /admin to /moderator

Changed routes from /admin to /moderator

---

src/components/grants/GrantContainer.jsx

new pr for seo branch

---

src/components/admin/GrantTable.jsx
src/components/grants/Logo/Logo.jsx
src/components/grants/Logo/defaultLogo.svg
src/components/grants/list/Grant.jsx
src/components/suggestion/SuggestionForm.jsx
src/store/grants/grantReducer.ts
src/store/grants/useGrantActions.tsx

Adding logo styles

---

src/components/grants/GrantShowcase.jsx
src/components/grants/list/GrantList.jsx
src/components/grants/list/NewGrant.tsx
src/components/grants/showcase/IconDisplay.jsx

Grants Container is now mobile
Appearances

Mobile Grants View

---

.env
src/components/admin/GrantTable.jsx
src/components/admin/GrantTableRow.jsx
src/components/admin/NewGrantTable.jsx
src/components/grants/Logo/Logo.jsx
src/components/grants/list/NewGrant.tsx
src/components/grants/showcase/ShowcaseTopContent.jsx
src/components/routing/Routes.jsx
src/store/admin/adminReducer.ts
src/store/admin/adminTypes.ts
src/store/admin/useAdminActions.tsx

Refactor of Suggestion Table is Complete

---

src/components/admin/AdminUserTable/UserTable.js
src/components/admin/GrantTable.jsx
src/components/filter/Filters.jsx
src/components/grants/GrantShowcase.jsx
src/components/grants/Logo/Logo.jsx
src/components/grants/list/NewGrant.tsx
src/components/grants/showcase/IconDisplay.jsx
src/components/grants/showcase/ShowcaseTopContent.jsx
src/components/navbar/Navbar.jsx
src/components/suggestion/SuggestionForm.jsx
src/hooks/useForm.jsx
src/store/filters/Filters.ts
src/store/filters/filterReducer.ts

Fixed Logo Performance Issues

---

src/components/grants/list/Grant.jsx
src/components/grants/list/NewGrant.tsx
src/components/grants/list/mobileGrantFields.js
src/components/grants/showcase/ShowcaseFields.jsx
src/components/grants/showcase/ShowcaseTopContent.jsx
src/utils/helpers.js

Styled Mobile Cards

---

src/components/suggestion/Suggestion.jsx
src/components/suggestion/suggestion.spec.js

my current  mess of tests rip

---

package-lock.json
package.json
src/components/grants/GrantContainer.jsx
src/components/grants/list/GrantList.jsx
src/components/suggestion/formElements/SubmitConfirmation.jsx
src/components/theme.js

Alert implemented with conditional rendering.
Applied conditional rendering to filter on grant container as well

Grant Alert

---

src/components/grants/showcase/ShowcaseTopContent.jsx
src/components/grants/showcase/WebsiteUrl.jsx

Updated Header Component to look nicer

Updated Header on Showcase Component

---

src/components/grants/showcase/ShowcaseTopContent.jsx
src/components/landingpage/LandingPage.jsx
src/components/landingpage/Welcome.jsx

Styling Fixes

---

src/components/about/About.jsx
src/components/filter/Filters.jsx
src/components/grants/GrantContainer.jsx
src/components/grants/GrantShowcase.jsx
src/components/grants/showcase/ShowcaseFields.jsx
src/components/grants/showcase/ShowcaseMainContent.jsx
src/components/grants/showcase/ShowcaseTopContent.jsx

Brave, oh so brave

---

src/components/userProfile/userData.js
src/components/userProfile/userSettings.js

Fixes Updates on User Settings

Fixed User Settings Update

---

src/store/admin/adminReducer.ts
src/store/admin/useAdminActions.tsx

Fixed Update Moderator Action And Reducer
No long errors out when promoting a moderator

Fixing UpdateModerator Action and Reducer

---

src/components/admin/EditGrantModal.jsx
src/components/admin/GrantTableRow.jsx
src/components/contact/ContactUsForm.jsx
src/components/contact/values/ContactFormValues.jsx
src/components/footer/Footer.jsx
src/components/routing/Routes.jsx
src/components/userProfile/UserSettingsForm.js
src/components/userProfile/userSettings.js
src/store/admin/adminReducer.ts
src/store/admin/adminTypes.ts
src/store/admin/useAdminActions.tsx

- [ x] New feature (non-breaking change which adds functionality)

Many features

---

package.json
src/components/admin/EditGrantModal.jsx
src/components/admin/GrantTableRow.jsx
src/components/admin/NewGrantTable.jsx
src/components/admin/values/EditGrantDialog.jsx
src/components/admin/values/EditGrantForm.jsx
src/components/admin/values/EditGrantFormValues.jsx
src/components/admin/values/EmailFormValues.jsx
src/components/userProfile/userSettings.js
src/store/grants/useGrantActions.tsx

Store changes + styling

---

src/components/admin/GrantTableRow.jsx
src/components/filter/Filters.jsx
src/components/landingpage/Welcome.jsx

Fixed Styling on About Button

---

src/components/admin/GrantTableRow.jsx

Fixed GrantTableRow

---

src/components/admin/AdminUserTable/values/UserTableValues.js
src/components/admin/EditGrantModal.jsx
src/components/admin/GrantTableRow.jsx
src/components/dialog/BaseDialog.jsx
src/components/navbar/Navbar.jsx
src/components/suggestion/SuggestionForm.jsx
src/components/suggestion/formElements/GrantFocusForm.jsx
src/components/suggestion/formElements/GrantInfoForm.jsx
src/components/suggestion/formElements/TextFormField.jsx
src/components/suggestion/formUtils/formValues.js
src/components/userProfile/UserSettingsForm.js
src/components/userProfile/userSettings.js
src/store/grants/useGrantActions.tsx

- [x ] New feature (non-breaking change which adds functionality)

Push for EditGrants

---

src/components/userProfile/userData.js

Testing Netifly Deploy with this PR

Removed Unused Import in UserData

---

src/components/admin/EditGrantModal.jsx
src/components/admin/values/EditGrantFormValues.jsx
src/components/admin/values/GrantTableValues.jsx
src/components/suggestion/SuggestionForm.jsx
src/components/suggestion/formUtils/formValues.js

- [x ] New feature (non-breaking change which adds functionality)

EDIT GRANTS

---

src/components/admin/EditGrantModal.jsx
src/components/suggestion/SuggestionForm.jsx

date fixed

---

src/components/admin/AdminUserTable/UserTable.js

added moderator filter

---

src/components/admin/AdminUserTable/UserTable.js
src/components/navbar/SideMenu.jsx
src/store/admin/adminReducer.ts
src/store/admin/adminTypes.ts
src/store/admin/useAdminActions.tsx

Promote Demote Moderators is working on FE

Promote Demote Moderators is working

---

src/components/about/About.jsx
src/components/suggestion/SuggestionForm.jsx

deleted hard values from SuggestionForm

---

src/components/dialog/BaseDialog.jsx

Fix Suggestions Not Submitting
Fix Suggestions Not Submitting

Fix Suggestions Not Submitting

---

src/components/admin/NewGrantTable.jsx
src/components/dialog/BaseDialog.jsx
src/components/grants/showcase/ShowcaseBottomContent.jsx
src/hooks/useForm.jsx

Fixed Bug where Suggestions where going to wrong id
Fixed Bug where Suggestions where going to wrong id

Fixed Bug where Suggestions where going to wrong id

---

.codeclimate.yml

Fixed exclude patterns on Code Climate

Fixed exclude patterns on Code Climate

---

src/components/filter/Filters.jsx
src/components/grants/GrantContainer.jsx

Is Filters Working Now

---

src/store/filters/Filters.ts
src/store/filters/filterReducer.ts
src/store/index.ts

Filters are now working

---

.codeclimate.yml
src/components/filter/formState.ts
src/components/grants/GrantContainer.jsx
src/store/filters/Filters.ts
src/store/filters/filterReducer.ts
src/store/filters/filterTypes.ts
src/store/index.ts

Ok they are now working as intended

Filters are NOW NOW Working

---

README.md
public/index.html
src/components/admin/NewGrantTable.jsx

admin table filters mvp

---

src/components/filter/FilterItem.tsx

maybe this?

---

src/components/filter/FilterGroup.tsx

Spencer did this one

---

package.json

this will fix safari issue for sure

---

src/components/filter/NewFilters.tsx

revert for testing

---

package-lock.json
src/components/filter/NewFilters.tsx
src/components/filter/formState.ts
src/store/filters/Filters.ts

Reverts Lambda-School-Labs/startup-grant-database-fe#236

Revert "Mango"

---

package.json
src/components/filter/NewFilters.tsx
src/components/filter/formState.ts
src/store/filters/Filters.ts

Freshmango

---

package.json
src/components/filter/NewFilters.tsx
src/components/filter/formState.ts
src/store/filters/Filters.ts

Reverts Lambda-School-Labs/startup-grant-database-fe#241

Revert "Freshmango"

---

src/store/filters/Filters.ts

Fixed Safari Bug with Filters
